export const authConstraints = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_FAILED: "SIGNOUT_FAILED",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    CHECKING_LOGIN_STATUS: "CHECKING_LOGIN_STATUS",
    USER_LOGGEDIN: "USER_LOGGEDIN",
    USER_NOT_FOUND: "USER_NOT_FOUND"

}

export const categoryConstraints = {
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_FAILED: "GET_ALL_CATEGORY_FAILED",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
};

export const productConstraints = {
    GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",
    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    SEARCH_PRODUCT_REQUEST: "SEARCH_PRODUCT_REQUEST",
    SEARCH_PRODUCT_FAILED: "SEARCH_PRODUCT_FAILED",
    SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
    SEARCH_PRODUCT_BY_CATEGORY_REQUEST: "SEARCH_PRODUCT_BY_CATEGORY_REQUEST",
    SEARCH_PRODUCT_BY_CATEGORY_FAILED: "SEARCH_PRODUCT_BY_CATEGORY_FAILED",
    SEARCH_PRODUCT_BY_CATEGORY_SUCCESS: "SEARCH_PRODUCT_BY_CATEGORY_SUCCESS",
    GET_PRODUCTS_BY_CATEGORY_REQUEST: "GET_PRODUCTS_BY_CATEGORY_REQUEST",
    GET_PRODUCTS_BY_CATEGORY_FAILED: "GET_PRODUCTS_BY_CATEGORY_FAILED",
    GET_PRODUCTS_BY_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_CATEGORY_SUCCESS",
    GET_PRODUCTS_BY_ROOT_CATEGORY_REQUEST: "GET_PRODUCTS_BY_ROOT_CATEGORY_REQUEST",
    GET_PRODUCTS_BY_ROOT_CATEGORY_FAILED: "GET_PRODUCTS_BY_ROOT_CATEGORY_FAILED",
    GET_PRODUCTS_BY_ROOT_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_ROOT_CATEGORY_SUCCESS",
    FILTER_PRODUCTS_BY_CATEGORY_REQUEST: "FILTER_PRODUCTS_BY_CATEGORY_REQUEST",
    FILTER_PRODUCTS_BY_CATEGORY_FAILED: "FILTER_PRODUCTS_BY_CATEGORY_FAILED",
    FILTER_PRODUCTS_BY_CATEGORY_SUCCESS: "FILTER_PRODUCTS_BY_CATEGORY_SUCCESS",
    FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_REQUEST: "FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_REQUEST",
    FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_FAILED: "FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_FAILED",
    FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_SUCCESS: "FILTER_PRODUCTS_BY_SUBROOT_CATEGORY_SUCCESS",
}